name: CI
on: [push]

jobs:
  sast_scan:
    name: Run sast scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: setup python
        uses: action/setup-python@v2
        with:
          python-version: 3.8

      - name: install Bandit
        run: pip install bandit

      - name: Run bandit scan
        run: bandit -r .
      


